In [90]:
import torch
import tensorflow as tf

In [91]:
"""
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Data/
"""

"\nfrom google.colab import drive\ndrive.mount('/content/drive')\n%cd /content/drive/My Drive/Data/\n"

In [92]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 6C2B-C4B4

 Directory of C:\Users\appadmin\Documents\ResearchMS

08/26/2022  03:28 PM    <DIR>          .
08/26/2022  03:28 PM    <DIR>          ..
08/26/2022  01:24 PM    <DIR>          .ipynb_checkpoints
08/25/2022  10:18 PM        39,740,139 concat_features.pt
08/26/2022  10:12 AM        10,724,075 concat_features_test.pt
08/25/2022  03:23 PM    <DIR>          en_images-20220825T063442Z-001
08/25/2022  12:10 PM       581,017,050 en_images-20220825T063442Z-001.zip
08/25/2022  09:10 PM    <DIR>          en_test_images-20220825T152147Z-001
08/26/2022  10:22 AM        17,349,050 Image_Caps_Embeddings-TestData.ipynb
08/26/2022  02:02 PM        17,993,062 Image_Caps_Embeddings.ipynb
08/25/2022  02:56 PM           328,827 image_captions.csv
08/25/2022  12:04 PM           636,992 Labels_A.csv
08/26/2022  10:07 AM           235,242 Labels_A_test_v1.csv
08/25/2022  09:08 PM           900,016 Labels_A_v1.csv
08/25/2022  10:15 PM           

In [93]:
#testing tensors capability 
pytorch_tensor = torch.load('val_tensor.pt')
np_tensor = pytorch_tensor.numpy()
tf_tensor = tf.convert_to_tensor(np_tensor)
pytorch_tensor_target = torch.load('val_tensor_target.pt')
np_tensor_target = pytorch_tensor_target.numpy()
tf_tensor_target = tf.convert_to_tensor(np_tensor_target)
#print(pytorch_tensor, np_tensor, tf_tensor)
#print(pytorch_tensor_target, np_tensor_target, tf_tensor_target)

In [94]:
#read training, target tensor
pt_tensor_train = torch.load('model_tensor.pt')
np_tensor_train = pt_tensor_train.numpy()
tf_tensor_train = tf.convert_to_tensor(np_tensor_train)
pt_tensor_train_target = torch.load('model_tensor_target.pt')
np_tensor_train_target = pt_tensor_train_target.numpy()
tf_tensor_train_target = tf.convert_to_tensor(np_tensor_train_target)
tf_tensor_train.shape, tf_tensor_train_target.shape

(TensorShape([5544, 1795]), TensorShape([5544, 1]))

In [95]:
#read valdation, target tensor
pt_tensor_val = torch.load('val_tensor.pt')
np_tensor_val = pt_tensor_val.numpy()
tf_tensor_val = tf.convert_to_tensor(np_tensor_val)
pt_tensor_val_target = torch.load('val_tensor_target.pt')
np_tensor_val_target = pt_tensor_val_target.numpy()
tf_tensor_val_target = tf.convert_to_tensor(np_tensor_val_target)
tf_tensor_val.shape, tf_tensor_val_target.shape

(TensorShape([1044, 1795]), TensorShape([1044, 1]))

In [96]:
#read testing, target tensor
pt_tensor_test = torch.load('test_tensor.pt')
np_tensor_test = pt_tensor_test.numpy()
tf_tensor_test = tf.convert_to_tensor(np_tensor_test)
pt_tensor_test_target = torch.load('test_tensor_target.pt')
np_tensor_test_target = pt_tensor_test_target.numpy()
tf_tensor_test_target = tf.convert_to_tensor(np_tensor_test_target)
tf_tensor_test.shape, tf_tensor_test_target.shape

(TensorShape([1496, 1795]), TensorShape([1496, 1]))

In [97]:
np_tensor_test_target.flatten().shape, type(np_tensor_test_target)

((1496,), numpy.ndarray)

In [98]:
import numpy as np

In [99]:
np_tensor_train

array([[ 0.0000000e+00,  1.1119392e+07,  7.0400000e+03, ...,
         4.4000000e+01,  8.0000000e+00,  0.0000000e+00],
       [-2.0190430e-01,  3.6962891e-01,  2.6269531e-01, ...,
         4.3000000e+01,  1.0000000e+01,  1.0000000e+00],
       [-3.1518555e-01,  7.0190430e-02, -2.3544312e-02, ...,
         6.6000000e+01,  1.5000000e+01, -1.0000000e+00],
       ...,
       [-2.9028320e-01,  2.6367188e-01, -5.4931641e-04, ...,
         1.2800000e+02,  1.9000000e+01,  0.0000000e+00],
       [-1.2588501e-02,  3.2379150e-02,  3.2177734e-01, ...,
         5.5000000e+01,  1.0000000e+01,  0.0000000e+00],
       [-4.7949219e-01, -1.1035156e-01,  1.3903809e-01, ...,
         1.1600000e+02,  1.9000000e+01, -1.0000000e+00]], dtype=float32)

In [100]:
np.reshape(np_tensor_train, (5544,1, 1795))

array([[[ 0.0000000e+00,  1.1119392e+07,  7.0400000e+03, ...,
          4.4000000e+01,  8.0000000e+00,  0.0000000e+00]],

       [[-2.0190430e-01,  3.6962891e-01,  2.6269531e-01, ...,
          4.3000000e+01,  1.0000000e+01,  1.0000000e+00]],

       [[-3.1518555e-01,  7.0190430e-02, -2.3544312e-02, ...,
          6.6000000e+01,  1.5000000e+01, -1.0000000e+00]],

       ...,

       [[-2.9028320e-01,  2.6367188e-01, -5.4931641e-04, ...,
          1.2800000e+02,  1.9000000e+01,  0.0000000e+00]],

       [[-1.2588501e-02,  3.2379150e-02,  3.2177734e-01, ...,
          5.5000000e+01,  1.0000000e+01,  0.0000000e+00]],

       [[-4.7949219e-01, -1.1035156e-01,  1.3903809e-01, ...,
          1.1600000e+02,  1.9000000e+01, -1.0000000e+00]]], dtype=float32)

In [101]:
type(np_tensor_train), np_tensor_train.shape

(numpy.ndarray, (5544, 1795))

In [102]:
train_target = np_tensor_train_target.flatten()
train_data = np.reshape(np_tensor_train, (5544,1,1795)) # np_tensor_train

In [103]:
train_data

array([[[ 0.0000000e+00,  1.1119392e+07,  7.0400000e+03, ...,
          4.4000000e+01,  8.0000000e+00,  0.0000000e+00]],

       [[-2.0190430e-01,  3.6962891e-01,  2.6269531e-01, ...,
          4.3000000e+01,  1.0000000e+01,  1.0000000e+00]],

       [[-3.1518555e-01,  7.0190430e-02, -2.3544312e-02, ...,
          6.6000000e+01,  1.5000000e+01, -1.0000000e+00]],

       ...,

       [[-2.9028320e-01,  2.6367188e-01, -5.4931641e-04, ...,
          1.2800000e+02,  1.9000000e+01,  0.0000000e+00]],

       [[-1.2588501e-02,  3.2379150e-02,  3.2177734e-01, ...,
          5.5000000e+01,  1.0000000e+01,  0.0000000e+00]],

       [[-4.7949219e-01, -1.1035156e-01,  1.3903809e-01, ...,
          1.1600000e+02,  1.9000000e+01, -1.0000000e+00]]], dtype=float32)

In [104]:
train_target.shape

(5544,)

In [105]:
train_target[train_target==-1] = 2

In [106]:
train_target.shape

(5544,)

In [107]:
!pip install tensorflow_addons

In [144]:
import numpy as np, pandas as pd
import tensorflow_addons as tfa

In [119]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, 1795)),
    #tf.keras.layers.Dense(512, activation='relu'),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(optimizer=tfa.optimizers.RectifiedAdam(0.0001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              #tf.keras.metrics.Accuracy, , tfa.metrics.F1Score
              metrics=['accuracy'])

In [120]:
train_target

array([1., 2., 0., ..., 0., 1., 1.], dtype=float32)

In [121]:
target = tf.keras.utils.to_categorical(
    train_target, num_classes=3, dtype='float32'
)
target.shape

(5544, 3)

In [129]:
history = model.fit(train_data, train_target, validation_split=0.45, epochs=50)

Epoch 1/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0743 - accuracy: 0.9800 - val_loss: 1.6514 - val_accuracy: 0.7053
Epoch 2/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0828 - accuracy: 0.9754 - val_loss: 1.6255 - val_accuracy: 0.7132
Epoch 3/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0705 - accuracy: 0.9793 - val_loss: 1.7794 - val_accuracy: 0.7136
Epoch 4/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0725 - accuracy: 0.9806 - val_loss: 1.7127 - val_accuracy: 0.7125
Epoch 5/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0689 - accuracy: 0.9823 - val_loss: 1.6102 - val_accuracy: 0.7002
Epoch 6/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0718 - accuracy: 0.9770 - val_loss: 1.6168 - val_accuracy: 0.7060
Epoch 7/50
96/96 [==============================] - 0s 5ms/step - loss: 0.0682 - accuracy: 0.9797 - val_loss: 1.6225 - val_accuracy: 0.7017
Epoch 8/50
96/96 [==

In [130]:
test_target = np_tensor_test_target.flatten()
test_data = np.reshape(np_tensor_test, (1496,1,1795)) # np_tensor_test

In [131]:
test_target[test_target==-1] = 2

In [132]:
test_loss, test_acc = model.evaluate(test_data,  test_target, verbose=2)

print('\nConfusion Matrix:', test_acc)

47/47 - 0s - loss: 190646691962028032.0000 - accuracy: 0.4412 - 81ms/epoch - 2ms/step

Confusion Matrix: 0.44117647409439087


In [133]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])

In [137]:
predictions_train = probability_model.predict(train_data)
predictions_train

array([[0.21194157, 0.5761169 , 0.21194157],
       [0.21733162, 0.22346786, 0.5592005 ],
       [0.5745643 , 0.21312536, 0.21231036],
       ...,
       [0.2119416 , 0.57611686, 0.21194157],
       [0.21246977, 0.5752986 , 0.21223162],
       [0.22000183, 0.56597286, 0.21402532]], dtype=float32)

In [138]:
predictions_test = probability_model.predict(test_data)
predictions_test

array([[0.21194157, 0.5761169 , 0.21194157],
       [0.2119469 , 0.5760931 , 0.21196   ],
       [0.21194246, 0.5761138 , 0.21194372],
       ...,
       [0.21194354, 0.57610923, 0.21194728],
       [0.21198255, 0.576064  , 0.21195342],
       [0.21194157, 0.5761169 , 0.21194157]], dtype=float32)

In [141]:
len(predictions_train), len(predictions_test)

(5544, 1496)

In [139]:
np.argmax(predictions_train[5]), train_target[5]

(1, 1.0)

In [140]:
np.argmax(predictions_test[5]), test_target[5]

(1, 0.0)

In [147]:
y_true_train, y_pred_train = [],[]
for i in range(len(predictions_train)):
    y_true_train.append(np.argmax(predictions_train[i]))
    y_pred_train.append(train_target[i])

train_result_df = pd.DataFrame(y_true_train, y_pred_train).reset_index()
train_result_df.columns = ['y_true_train', 'y_pred_train']
train_result_df.head()

y_true_train  y_pred_train
0           1.0             1
1           2.0             2
2           0.0             0
3           1.0             1
4           1.0             1

In [148]:
y_true_test, y_pred_test = [],[]
for i in range(len(predictions_test)):
    y_true_test.append(np.argmax(predictions_test[i]))
    y_pred_test.append(test_target[i])

test_result_df = pd.DataFrame(y_true_test, y_pred_test).reset_index()
test_result_df.columns = ['y_true_test', 'y_pred_tes']
test_result_df.head()

y_true_test  y_pred_tes
0          0.0           1
1          1.0           1
2          1.0           1
3          1.0           1
4          2.0           1

In [159]:
train_result_df.to_csv('train_result.csv', index=False)
test_result_df.to_csv('test_result.csv', index=False)

In [150]:
from sklearn.metrics import confusion_matrix

In [152]:
confusion_matrix(y_true_train, y_pred_train)

array([[1329,  249,   38],
       [ 351, 3021,  101],
       [  35,   56,  364]], dtype=int64)

In [153]:
confusion_matrix(y_true_test, y_pred_test)

array([[ 45, 157,  96],
       [120, 588, 397],
       [ 12,  54,  27]], dtype=int64)

In [154]:
from sklearn.metrics import f1_score

In [156]:
f1_score(y_true_train, y_pred_train, zero_division=1, average='micro')

0.8502886002886003

In [157]:
f1_score(y_true_test, y_pred_test, zero_division=1, average='micro')

0.4411764705882353

In [160]:
from sklearn.metrics import accuracy_score, recall_score

In [162]:
accuracy_score(y_true_test, y_pred_test)

0.4411764705882353

In [165]:
recall_score(y_true_test, y_pred_test, zero_division=1, average='micro')

0.4411764705882353

# ###############################################################
# End of Model Training and Testing

In [126]:
target_test = tf.keras.utils.to_categorical(
    test_target, num_classes=3, dtype='float32'
)
target_test.shape

(1496, 3)

In [41]:
history_dict = history.history
history_dict.keys()

dict_keys(['loss', 'f1_score', 'val_loss', 'val_f1_score'])

In [40]:
train_target = np_tensor_train_target.flatten()
train_data = np.reshape(np_tensor_train, (4500,1,1795)) # np_tensor_train

In [41]:
train_target.shape

(4500,)

In [42]:
train_target[train_target==-1] = 2

In [43]:
#?model.fit

In [44]:
val_target = np_tensor_val_target.flatten()
val_data = np.reshape(np_tensor_val, (1044,1,1795)) # np_tensor_test

In [45]:
val_target[val_target==-1] = 2

In [46]:
test_target = np_tensor_test_target.flatten()
test_data = np.reshape(np_tensor_test, (1496,1,1795)) # np_tensor_test

In [47]:
test_target[test_target==-1] = 2

In [38]:
import numpy as np, pandas as pd
import matplotlib.pyplot as plt

In [25]:
"""acc = history_dict['accuracy']
val_acc = history_dict['val_accuracy']
loss = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

# "bo" is for "blue dot"
plt.plot(epochs, loss, 'bo', label='Training loss')
# b is for "solid blue line"
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()"""

'acc = history_dict[\'accuracy\']\nval_acc = history_dict[\'val_accuracy\']\nloss = history_dict[\'loss\']\nval_loss = history_dict[\'val_loss\']\n\nepochs = range(1, len(acc) + 1)\n\n# "bo" is for "blue dot"\nplt.plot(epochs, loss, \'bo\', label=\'Training loss\')\n# b is for "solid blue line"\nplt.plot(epochs, val_loss, \'b\', label=\'Validation loss\')\nplt.title(\'Training and validation loss\')\nplt.xlabel(\'Epochs\')\nplt.ylabel(\'Loss\')\nplt.legend()\n\nplt.show()'

In [56]:
#set random seed
tf.random.set_seed(42)
#create the model
model_12=tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, 1795)),
    #tf.keras.layers.Dense(512,activation="relu"),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32,activation="relu"),
    tf.keras.layers.Dense(3,activation="softmax")
])

#compile the model
model_12.compile(
   loss=tf.keras.losses.SparseCategoricalCrossentropy(),
   optimizer=tf.keras.optimizers.Adam(),
   metrics="accuracy")

#create a learning rate callback
lr_scheduler = tf.keras.callbacks.LearningRateScheduler(lambda epoch : 0.005)

#fit the model
fit_lr_history = model_12.fit(
   train_data,
   train_target,
   epochs=40,
   callbacks=[lr_scheduler],
   validation_data=(val_data,val_target))

Epoch 1/40
141/141 [==============================] - 1s 3ms/step - loss: 1465168097705984.0000 - accuracy: 0.5678 - val_loss: 0.8687 - val_accuracy: 0.6226 - lr: 0.0050
Epoch 2/40
141/141 [==============================] - 0s 2ms/step - loss: 0.8987 - accuracy: 0.5927 - val_loss: 0.8838 - val_accuracy: 0.6226 - lr: 0.0050
Epoch 3/40
141/141 [==============================] - 0s 2ms/step - loss: 0.8982 - accuracy: 0.5927 - val_loss: 0.8660 - val_accuracy: 0.6226 - lr: 0.0050
Epoch 4/40
141/141 [==============================] - 0s 2ms/step - loss: 0.8886 - accuracy: 0.5927 - val_loss: 0.8739 - val_accuracy: 0.6226 - lr: 0.0050
Epoch 5/40
141/141 [==============================] - 0s 2ms/step - loss: 0.8791 - accuracy: 0.5962 - val_loss: 0.8736 - val_accuracy: 0.6236 - lr: 0.0050
Epoch 6/40
141/141 [==============================] - 0s 2ms/step - loss: 0.8695 - accuracy: 0.5958 - val_loss: 0.8755 - val_accuracy: 0.6226 - lr: 0.0050
Epoch 7/40
141/141 [==============================] - 0