In [1]:
import torch
import tensorflow as tf

In [2]:
"""
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Data/
"""

"\nfrom google.colab import drive\ndrive.mount('/content/drive')\n%cd /content/drive/My Drive/Data/\n"

In [3]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 6C2B-C4B4

 Directory of C:\Users\appadmin\Documents\ResearchMS

08/26/2022  04:27 PM    <DIR>          .
08/26/2022  04:27 PM    <DIR>          ..
08/26/2022  04:27 PM    <DIR>          .ipynb_checkpoints
08/25/2022  10:18 PM        39,740,139 concat_features.pt
08/26/2022  10:12 AM        10,724,075 concat_features_test.pt
08/25/2022  03:23 PM    <DIR>          en_images-20220825T063442Z-001
08/25/2022  12:10 PM       581,017,050 en_images-20220825T063442Z-001.zip
08/25/2022  09:10 PM    <DIR>          en_test_images-20220825T152147Z-001
08/26/2022  10:22 AM        17,349,050 Image_Caps_Embeddings-TestData.ipynb
08/26/2022  02:02 PM        17,993,062 Image_Caps_Embeddings.ipynb
08/25/2022  02:56 PM           328,827 image_captions.csv
08/25/2022  12:04 PM           636,992 Labels_A.csv
08/26/2022  10:07 AM           235,242 Labels_A_test_v1.csv
08/25/2022  09:08 PM           900,016 Labels_A_v1.csv
08/25/2022  10:15 PM           

In [4]:
#testing tensors capability 
pytorch_tensor = torch.load('val_tensor.pt')
np_tensor = pytorch_tensor.numpy()
tf_tensor = tf.convert_to_tensor(np_tensor)
pytorch_tensor_target = torch.load('val_tensor_target.pt')
np_tensor_target = pytorch_tensor_target.numpy()
tf_tensor_target = tf.convert_to_tensor(np_tensor_target)
#print(pytorch_tensor, np_tensor, tf_tensor)
#print(pytorch_tensor_target, np_tensor_target, tf_tensor_target)

In [5]:
#read training, target tensor
pt_tensor_train = torch.load('train_tensor.pt')
np_tensor_train = pt_tensor_train.numpy()
tf_tensor_train = tf.convert_to_tensor(np_tensor_train)
pt_tensor_train_target = torch.load('train_tensor_target.pt')
np_tensor_train_target = pt_tensor_train_target.numpy()
tf_tensor_train_target = tf.convert_to_tensor(np_tensor_train_target)
tf_tensor_train.shape, tf_tensor_train_target.shape

(TensorShape([4500, 1795]), TensorShape([4500, 1]))

In [6]:
#read valdation, target tensor
pt_tensor_val = torch.load('val_tensor.pt')
np_tensor_val = pt_tensor_val.numpy()
tf_tensor_val = tf.convert_to_tensor(np_tensor_val)
pt_tensor_val_target = torch.load('val_tensor_target.pt')
np_tensor_val_target = pt_tensor_val_target.numpy()
tf_tensor_val_target = tf.convert_to_tensor(np_tensor_val_target)
tf_tensor_val.shape, tf_tensor_val_target.shape

(TensorShape([1044, 1795]), TensorShape([1044, 1]))

In [7]:
#read testing, target tensor
pt_tensor_test = torch.load('test_tensor.pt')
np_tensor_test = pt_tensor_test.numpy()
tf_tensor_test = tf.convert_to_tensor(np_tensor_test)
pt_tensor_test_target = torch.load('test_tensor_target.pt')
np_tensor_test_target = pt_tensor_test_target.numpy()
tf_tensor_test_target = tf.convert_to_tensor(np_tensor_test_target)
tf_tensor_test.shape, tf_tensor_test_target.shape

(TensorShape([1496, 1795]), TensorShape([1496, 1]))

In [8]:
np_tensor_test_target.flatten().shape, type(np_tensor_test_target)

((1496,), numpy.ndarray)

In [9]:
import numpy as np

In [10]:
np_tensor_train

array([[ 0.00000000e+00,  1.11193920e+07,  7.04000000e+03, ...,
         4.40000000e+01,  8.00000000e+00,  0.00000000e+00],
       [-2.01904297e-01,  3.69628906e-01,  2.62695312e-01, ...,
         4.30000000e+01,  1.00000000e+01,  1.00000000e+00],
       [-3.15185547e-01,  7.01904297e-02, -2.35443115e-02, ...,
         6.60000000e+01,  1.50000000e+01, -1.00000000e+00],
       ...,
       [-5.79101562e-01, -1.05041504e-01,  9.94873047e-02, ...,
         9.20000000e+01,  1.50000000e+01, -1.00000000e+00],
       [-5.62011719e-01, -4.56542969e-01, -1.09130859e-01, ...,
         6.80000000e+01,  1.40000000e+01, -1.00000000e+00],
       [-5.62988281e-01,  2.04589844e-01, -4.97436523e-02, ...,
         5.80000000e+01,  1.20000000e+01,  0.00000000e+00]], dtype=float32)

In [11]:
np.reshape(np_tensor_train, (4500,1, 1795))

array([[[ 0.00000000e+00,  1.11193920e+07,  7.04000000e+03, ...,
          4.40000000e+01,  8.00000000e+00,  0.00000000e+00]],

       [[-2.01904297e-01,  3.69628906e-01,  2.62695312e-01, ...,
          4.30000000e+01,  1.00000000e+01,  1.00000000e+00]],

       [[-3.15185547e-01,  7.01904297e-02, -2.35443115e-02, ...,
          6.60000000e+01,  1.50000000e+01, -1.00000000e+00]],

       ...,

       [[-5.79101562e-01, -1.05041504e-01,  9.94873047e-02, ...,
          9.20000000e+01,  1.50000000e+01, -1.00000000e+00]],

       [[-5.62011719e-01, -4.56542969e-01, -1.09130859e-01, ...,
          6.80000000e+01,  1.40000000e+01, -1.00000000e+00]],

       [[-5.62988281e-01,  2.04589844e-01, -4.97436523e-02, ...,
          5.80000000e+01,  1.20000000e+01,  0.00000000e+00]]],
      dtype=float32)

In [12]:
type(np_tensor_train), np_tensor_train.shape

(numpy.ndarray, (4500, 1795))

In [13]:
train_target = np_tensor_train_target.flatten()
train_data = np.reshape(np_tensor_train, (4500,1,1795)) # np_tensor_train

In [14]:
test_target = np_tensor_val_target.flatten()
test_data = np.reshape(np_tensor_val, (1044,1,1795)) # np_tensor_test

In [15]:
train_data

array([[[ 0.00000000e+00,  1.11193920e+07,  7.04000000e+03, ...,
          4.40000000e+01,  8.00000000e+00,  0.00000000e+00]],

       [[-2.01904297e-01,  3.69628906e-01,  2.62695312e-01, ...,
          4.30000000e+01,  1.00000000e+01,  1.00000000e+00]],

       [[-3.15185547e-01,  7.01904297e-02, -2.35443115e-02, ...,
          6.60000000e+01,  1.50000000e+01, -1.00000000e+00]],

       ...,

       [[-5.79101562e-01, -1.05041504e-01,  9.94873047e-02, ...,
          9.20000000e+01,  1.50000000e+01, -1.00000000e+00]],

       [[-5.62011719e-01, -4.56542969e-01, -1.09130859e-01, ...,
          6.80000000e+01,  1.40000000e+01, -1.00000000e+00]],

       [[-5.62988281e-01,  2.04589844e-01, -4.97436523e-02, ...,
          5.80000000e+01,  1.20000000e+01,  0.00000000e+00]]],
      dtype=float32)

In [16]:
train_target.shape

(4500,)

In [17]:
train_target[train_target==-1] = 2

In [18]:
test_target[test_target==-1] = 2

In [19]:
train_target.shape

(4500,)

In [20]:
!pip install tensorflow_addons

In [21]:
import numpy as np, pandas as pd
import tensorflow_addons as tfa

In [43]:
tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, 1795)),
    #tf.keras.layers.Dense(512, activation='relu'),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(optimizer=tfa.optimizers.RectifiedAdam(0.0001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              #tf.keras.metrics.Accuracy, , tfa.metrics.F1Score
              metrics=['accuracy'])

In [44]:
train_target

array([1., 2., 0., ..., 0., 2., 1.], dtype=float32)

In [45]:
target = tf.keras.utils.to_categorical(
    train_target, num_classes=3, dtype='float32'
)
target.shape

(4500, 3)

In [70]:
history = model.fit(train_data, train_target, validation_split=0.40, epochs=50)

Epoch 1/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0444 - accuracy: 0.9874 - val_loss: 1.1866 - val_accuracy: 0.7683
Epoch 2/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0478 - accuracy: 0.9874 - val_loss: 1.1799 - val_accuracy: 0.7617
Epoch 3/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0507 - accuracy: 0.9870 - val_loss: 1.2454 - val_accuracy: 0.7689
Epoch 4/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0452 - accuracy: 0.9889 - val_loss: 1.1942 - val_accuracy: 0.7678
Epoch 5/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0573 - accuracy: 0.9837 - val_loss: 1.2021 - val_accuracy: 0.7661
Epoch 6/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0399 - accuracy: 0.9896 - val_loss: 1.1978 - val_accuracy: 0.7644
Epoch 7/50
85/85 [==============================] - 0s 3ms/step - loss: 0.0475 - accuracy: 0.9885 - val_loss: 1.2493 - val_accuracy: 0.7672
Epoch 8/50
85/85 [==

In [71]:
test_loss, test_acc = model.evaluate(test_data,  test_target, verbose=2)

print('\nConfusion Matrix:', test_acc)

33/33 - 0s - loss: 3.1848 - accuracy: 0.5335 - 44ms/epoch - 1ms/step

Confusion Matrix: 0.5335249304771423


In [72]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])

In [73]:
predictions_train = probability_model.predict(train_data)
predictions_train

array([[0.21194157, 0.5761169 , 0.21194157],
       [0.21215226, 0.21247682, 0.57537097],
       [0.5709596 , 0.21601771, 0.21302268],
       ...,
       [0.21194553, 0.5760979 , 0.21195649],
       [0.21260785, 0.575212  , 0.2121801 ],
       [0.21591042, 0.5710887 , 0.21300091]], dtype=float32)

In [74]:
predictions_test = probability_model.predict(test_data)
predictions_test

array([[0.29428715, 0.26685268, 0.43886018],
       [0.2137314 , 0.5737546 , 0.21251404],
       [0.23893109, 0.4439642 , 0.31710467],
       ...,
       [0.21543577, 0.57170194, 0.21286222],
       [0.57460636, 0.21312913, 0.21226452],
       [0.21194158, 0.5761168 , 0.21194163]], dtype=float32)

In [75]:
len(predictions_train), len(predictions_test)

(4500, 1044)

In [76]:
np.argmax(predictions_train[5]), train_target[5]

(1, 1.0)

In [77]:
np.argmax(predictions_test[5]), test_target[5]

(2, 1.0)

In [78]:
y_true_train, y_pred_train = [],[]
for i in range(len(predictions_train)):
    y_true_train.append(np.argmax(predictions_train[i]))
    y_pred_train.append(train_target[i])

train_result_df = pd.DataFrame(y_true_train, y_pred_train).reset_index()
train_result_df.columns = ['y_true_train', 'y_pred_train']
train_result_df.head()

y_true_train  y_pred_train
0           1.0             1
1           2.0             2
2           0.0             0
3           1.0             1
4           1.0             1

In [79]:
y_true_test, y_pred_test = [],[]
for i in range(len(predictions_test)):
    y_true_test.append(np.argmax(predictions_test[i]))
    y_pred_test.append(test_target[i])

test_result_df = pd.DataFrame(y_true_test, y_pred_test).reset_index()
test_result_df.columns = ['y_true_test', 'y_pred_tes']
test_result_df.head()

y_true_test  y_pred_tes
0          1.0           2
1          0.0           1
2          1.0           1
3          1.0           1
4          1.0           2

In [80]:
train_result_df.to_csv('train_result_2.csv', index=False)
test_result_df.to_csv('test_result_2.csv', index=False)

In [81]:
from sklearn.metrics import confusion_matrix

In [82]:
confusion_matrix(y_true_train, y_pred_train)

array([[1184,  103,   12],
       [ 209, 2552,   83],
       [  13,   21,  323]], dtype=int64)

In [83]:
confusion_matrix(y_true_test, y_pred_test)

array([[ 65, 132,  24],
       [234, 487,  56],
       [ 10,  31,   5]], dtype=int64)

In [84]:
from sklearn.metrics import f1_score

In [85]:
f1_score(y_true_train, y_pred_train, zero_division=1, average='micro')

0.902

In [91]:
accuracy_score(y_true_train, y_pred_train)

0.902

In [92]:
recall_score(y_true_train, y_pred_train, zero_division=1, average='micro')

0.902

In [86]:
f1_score(y_true_test, y_pred_test, zero_division=1, average='micro')

0.5335249042145593

In [88]:
from sklearn.metrics import accuracy_score, recall_score

In [89]:
accuracy_score(y_true_test, y_pred_test)

0.5335249042145593

In [90]:
recall_score(y_true_test, y_pred_test, zero_division=1, average='micro')

0.5335249042145593

# ###############################################################
# End of Model Training and Testing